### ISSUE TITLE
Add support for Severity Rating Scale

### ISSUE THREAD

**Issue by mkoppmann** [mkoppmann/wtcvss#3]
The application should support the [Severity Rating Scale](https://www.first.org/cvss/v3.1/specification-document#Qualitative-Severity-Rating-Scale) so it can display the rating with the vector. This can also be used by the design.

**Comment by Jakobu5** [comment]
Assign me to this issue please

**Comment by mkoppmann** [comment]
Fixed in https://github.com/mkoppmann/wtcvss/commit/9d799f106df7f83247750bdd627618756c0900a5
